[build]
  # Build command
  command = "npm run build"

  # Publish directory for static files
  publish = "dist"

  # Functions directory for serverless functions
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.9"
  PYTHONPATH = "/opt/buildhome/repo/netlify/functions"

# Discord OAuth routes - serve callback page directly
[[redirects]]
  from = "/discord/callback"
  to = "/discord-callback.html"
  status = 200

# API routes to serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Direct verify route to serverless function
[[redirects]]
  from = "/verify"
  to = "/.netlify/functions/api"
  status = 200

# Redirect verification routes to serverless functions
[[redirects]]
  from = "/verify*"
  to = "/.netlify/functions/:splat"
  status = 200

# Redirect admin routes
[[redirects]]
  from = "/admin/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Static file serving
[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200

# Handle root and fallback - main page is verify.html (served as index.html)
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

# SPA fallback - handle all other routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Specific routes for verification pages
[[redirects]]
  from = "/verify"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/verify-auto"
  to = "/verify-auto.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"